### ISSUE TITLE
Readme minetestmapper link

### ISSUE THREAD

**Issue by HybridDog** [est31/leaftest#11]
The link in the readme should direct to https://github.com/minetest/minetestmapper, shouldn't it?

**Comment by est31** [comment]
No, I was pointing to the fork . See #9. But the PR to make it compatible to the new mapblock format still hasn't been merged yet (its linked in the issue I referenced) so you need to use a fork of the fork that is compatible to the mapblock format.

**Comment by HybridDog** [comment]
Looks like I'm the third one.
