### ISSUE TITLE
A warning about `JOBNUM`

### ISSUE THREAD

**Issue by VanessaE** [est31/leaftest#20]
If using a modern version of @Rogier-5's mapper fork, you cannot safely set leaftest's number of jobs higher than 1, if the map database uses the leveldb backend - the mapper process will bail out, complaining about locking failures (resource temporarily unavailable).

You should probably add such a comment to your readme.

**Comment by est31** [comment]
Hi @VanessaE do you know of a link to an updated version of the fork?

**Comment by VanessaE** [comment]
I just pull from Rogier's repository, https://github.com/Rogier-5/minetest-mapper-cpp

**Comment by est31** [comment]
That works? thought you needed a patch: https://github.com/Rogier-5/minetest-mapper-cpp/pull/20 or have you applied that locally?

**Comment by VanessaE** [comment]
Yes, it works fine so long as these few lines from sfan5's commit are applied, https://github.com/minetest/minetestmapper/commit/21444d00c35dc6896ffc27af7da38d8a296178fd

(the pull request you linked to is outdated, sfan5's patch is sufficient)

**Comment by est31** [comment]
Oh ok. I don't know which precise wording you'd prefer. Do you want to file a PR?

**Comment by VanessaE** [comment]
I would just put "Do not set this above 1 if the world uses the LevelDB backend" somewhere appropriate.

**Comment by est31** [comment]
Done.
