### ISSUE TITLE
dimension

### ISSUE THREAD

**Issue by 00c** [est31/leaftest#3]
Hi, thanks for great tool.
What is correct way to calculate dimension of any map? 
in minetestmapper i use following:

> --min-y -10 --max-y 70  --scalefactor 1:1 --geometry -4500,-4500:4500,4500

Map size 9000x9000 

> ./mapper.sh path/to/world **spawnx,spawny dimension**

What is map size x,y,z in this example?

> The dimension number specifies the width and height of the map that should be rendered, centering with your spawn position. dimension should be a multiple of 8*256 = 2048. 6144 is a good starting value.

**Comment by est31** [comment]
The total size of the area mapped is **dimension** x **dimension**, centered at the spawn node.

**Comment by est31** [comment]
If this answered your question, can you close this issue :), otherwise ask.

**Comment by 00c** [comment]
Can you give some example please. Map size and dimension

**Comment by 00c** [comment]
Example map size, spawn is at center what number use in 

> ./mapper.sh path/to/world **spawnx,spawny dimension**

**Comment by est31** [comment]
You can do:

```
./mapper.sh path/to/world 0,0 10240
```

It gives you a map of size 10240x10240. dimension should be a multiple of 2048.

**Comment by 00c** [comment]
Hey i got working map, used settings you gave me. Thanks
So i can use junks of 2048?
