### ISSUE TITLE
Not title tag

### ISSUE THREAD

**Issue by lightonflux** [est31/leaftest#5]
There is no title tag in the map.html. Is that intentional or just forgotten?

**Comment by est31** [comment]
IDk, what title tag would you suggest?

**Comment by est31** [comment]
Maybe it should be customizeable?

**Comment by lightonflux** [comment]
That's my thinking. Otherwise i would have pushed my local commit. If we add a title text that does not fit and people change it they no longer can update from git. :(

But maybe a generic "Minetest Map" or similar would be good enough.

**Comment by fireglow** [comment]
That would work.
A generic one is better than no title at all, imo.

**Comment by sbrl** [comment]
I can submit a PR, if that would be helpful?

**Comment by est31** [comment]
@sbrl definitely!

**Comment by sbrl** [comment]
Done. Also I know it's unrelated to this issue, but I've tweaked the stylesheet in my clone a bit to make it appear full screen & changed the font. Would you like a PR for that too? If so then I'll do that one once #5 has been dealt with.
