### ISSUE TITLE
 new MapBlock serialization

### ISSUE THREAD

**Issue by 00c** [est31/leaftest#7]
leaftest does not work with recent minetestmapper

`[TILEGEN 20/map_0_0.png]: minetestmapper [options]
[TILEGEN 20/map_0_0.png]: -i/--input <world_path>
[TILEGEN 20/map_0_0.png]: -o/--output <output_image.png>
[TILEGEN 20/map_0_0.png]: --bgcolor <color>
[TILEGEN 20/map_0_0.png]: --scalecolor <color>
[TILEGEN 20/map_0_0.png]: --playercolor <color>
[TILEGEN 20/map_0_0.png]: --origincolor <color>
[TILEGEN 20/map_0_0.png]: --drawscale
[TILEGEN 20/map_0_0.png]: --drawplayers
[TILEGEN 20/map_0_0.png]: --draworigin
[TILEGEN 20/map_0_0.png]: --drawalpha
[TILEGEN 20/map_0_0.png]: --noshading
[TILEGEN 20/map_0_0.png]: --min-y <y>
[TILEGEN 20/map_0_0.png]: --max-y <y>
[TILEGEN 20/map_0_0.png]: --backend <backend>
[TILEGEN 20/map_0_0.png]: --geometry x:y+w+h
[TILEGEN 20/map_0_0.png]: --zoom <zoomlevel>
[TILEGEN 20/map_0_0.png]: --colors <colors.txt>
[TILEGEN 20/map_0_0.png]: --scales [t][b][l][r]
[TILEGEN 20/map_0_0.png]: Color format: '#000000'
[TILEGEN 20/map_0_1.png]: minetestmapper [options]
[TILEGEN 20/map_0_1.png]: -i/--input <world_path>
[TILEGEN 20/map_0_1.png]: -o/--output <output_image.png>
[TILEGEN 20/map_0_1.png]: --bgcolor <color>
[TILEGEN 20/map_0_1.png]: --scalecolor <color>
[TILEGEN 20/map_0_1.png]: --playercolor <color>
[TILEGEN 20/map_0_1.png]: --origincolor <color>
[TILEGEN 20/map_0_2.png]: minetestmapper [options]
[TILEGEN 20/map_0_1.png]: --drawscale
[TILEGEN 20/map_0_1.png]: --drawplayers
[TILEGEN 20/map_0_2.png]: -i/--input <world_path>
[TILEGEN 20/map_0_1.png]: --draworigin
[TILEGEN 20/map_0_1.png]: --drawalpha
[TILEGEN 20/map_0_2.png]: -o/--output <output_image.png>
[TILEGEN 20/map_0_1.png]: --noshading
[TILEGEN 20/map_0_2.png]: --bgcolor <color>
[TILEGEN 20/map_0_1.png]: --min-y <y>
[TILEGEN 20/map_0_2.png]: --scalecolor <color>
[TILEGEN 20/map_0_1.png]: --max-y <y>
[TILEGEN 20/map_0_2.png]: --playercolor <color>
[TILEGEN 20/map_0_1.png]: --backend <backend>
[TILEGEN 20/map_0_2.png]: --origincolor <color>
[TILEGEN 20/map_0_1.png]: --geometry x:y+w+h
[TILEGEN 20/map_0_2.png]: --drawscale
[TILEGEN 20/map_0_2.png]: --drawplayers
[TILEGEN 20/map_0_2.png]: --draworigin
[TILEGEN 20/map_0_1.png]: --zoom <zoomlevel>
[TILEGEN 20/map_0_2.png]: --drawalpha
[TILEGEN 20/map_0_2.png]: --noshading
[TILEGEN 20/map_0_1.png]: --colors <colors.txt>
[TILEGEN 20/map_0_2.png]: --min-y <y>
[TILEGEN 20/map_0_1.png]: --scales [t][b][l][r]
[TILEGEN 20/map_0_2.png]: --max-y <y>
[TILEGEN 20/map_0_1.png]: Color format: '#000000'
[TILEGEN 20/map_0_2.png]: --backend <backend>
[TILEGEN 20/map_0_2.png]: --geometry x:y+w+h
[TILEGEN 20/map_0_2.png]: --zoom <zoomlevel>
minetesmapper for tile [0,0] ended with non zero exit code
[TILEGEN 20/map_0_2.png]: --colors <colors.txt>
[TILEGEN 20/map_0_2.png]: --scales [t][b][l][r]
[TILEGEN 20/map_0_2.png]: Color format: '#000000'
minetesmapper for tile [0,1] ended with non zero exit code
xargs: bash: exited with status 255; aborting
minetesmapper for tile [0,2] ended with non zero exit code
xargs: bash: exited with status 255; aborting
Error: xargs ended with non-zero exit code 124.
`

**Comment by est31** [comment]
@00c you are using the official minetestmapper? That one is not supported by leaftest. leaftest uses a non supported option. Use rogier's instead, once this issue is fixed: https://github.com/Rogier-5/minetest-mapper-cpp/issues/21.

**Comment by 00c** [comment]
Is there any other version that work with leaftest?
